---
- name: copy syslog-ng.service
  template: src=syslog-ng.service
            dest=/lib/systemd/syslog-ng.service
            owner=root
            group=root
            mode=0644
  notify: restart syslog-ng
